blog/urls.py
from django.conf.urls import url
from blog import views


urlpatterns = [
    url(r'(.*)/article/(\d+)/$', views.article_detail),
    url(r'(.*)/(category|tag|archive)/(.*)/$', views.home),
    url(r'(.*)/$', views.home),
]

d79_bbs/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog import views
from django.views.static import serve
from django.conf import settings
from blog import urls as blog_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', views.login),
    url(r'^index/', views.index),
    url(r'^v_code/', views.v_code),
    url(r'^login2/', views.login2),
    # 极验科技 获取验证码的url
    url(r'^pcgetcaptcha/', views.pcgetcaptcha),

    url(r'^reg/$', views.reg),


    url(r'logout/', views.logout),
    url(r'^blog/', include(blog_urls)),

    url(r'media/(?P<path>.*)$', serve, {"document_root":settings.MEDIA_ROOT}),

    url(r'test/', views.test),
    url(r'updown/', views.updown),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class UserInfo(AbstractUser):
    nid = models.AutoField(primary_key=True)
    phone = models.CharField(max_length=11, null=True, unique=True)
    avatar = models.FileField(upload_to="avatars/", default="avatars/default.png")

    blog = models.OneToOneField(to="Blog", to_field="nid", null=True)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = "用户信息"
        verbose_name_plural = verbose_name


class Blog(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=64)
    theme = models.CharField(max_length=32)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "博客"
        verbose_name_plural = verbose_name


class Category(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32)
    blog = models.ForeignKey(to="Blog", to_field="nid")

    def __str__(self):
        return "{}-{}".format(self.blog.title, self.title)

    class Meta:
        verbose_name = "文章分类"
        verbose_name_plural = verbose_name


class Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32)
    blog = models.ForeignKey(to="Blog", to_field="nid")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = verbose_name


class Article(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=64, verbose_name="标贴")
    desc = models.CharField(max_length=255)
    create_time = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(to="Category", to_field="nid", null=True)
    user = models.ForeignKey(to="UserInfo", to_field="nid")

    comment_count = models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)

    tags = models.ManyToManyField(
        to="Tag",
        through="Article2Tag",
        through_fields=("article", "tag")
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name


class ArticleDetail(models.Model):
    nid = models.AutoField(primary_key=True)
    content = models.TextField()
    article = models.OneToOneField(to="Article", to_field="nid")

    class Meta:
        verbose_name = "文章详情"
        verbose_name_plural = verbose_name


class Article2Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to="Article", to_field="nid")
    tag = models.ForeignKey(to="Tag", to_field="nid")

    def __str__(self):
        return "{}-{}".format(self.article, self.tag)

    class Meta:
        unique_together = ("article", "tag")
        verbose_name = "文章-标签"
        verbose_name_plural = verbose_name


class ArticleUpDown(models.Model):
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey(to="UserInfo", null=True)
    article = models.ForeignKey(to="Article", null=True)
    is_up = models.BooleanField(default=True)

    class Meta:
        unique_together = ("article", "user")
        verbose_name = "点赞"
        verbose_name_plural = verbose_name


class Comment(models.Model):
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to="Article", to_field="nid")
    user = models.ForeignKey(to="UserInfo", to_field="nid")
    content = models.CharField(max_length=255)
    create_time = models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey("self", null=True, blank=True)

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = verbose_name

blog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from blog import models


class LoginForm(forms.Form):
    username = forms.CharField(
        label="用户名",
        min_length=3,
        max_length=12,
        error_messages={
            "required": "用户名不能为空",
            "min_length": "用户名最短3位",
            "max_length": "用户名最长12位",
        },
        widget=forms.widgets.TextInput(
            attrs={"class": "form-control c1"}
        )
    )

    password = forms.CharField(
        label="密码",
        min_length=4,
        max_length=12,
        error_messages={
            "required": "用户名不能为空",
            "min_length": "用户密码最短4位",
            "max_length": "用户密码最长12位",
        },
        widget=forms.widgets.PasswordInput(
            attrs={"class": "form-control"}
        )
    )


class RegForm(forms.Form):
    username = forms.CharField(
        label="用户名",
        min_length=3,
        max_length=12,
        error_messages={
            "required": "用户名不能为空",
            "min_length": "密码最短4位",
            "max_length": "密码最长12位"
        },
        widget=forms.widgets.TextInput(
            attrs={"class": "form-control"}
        )
    )

    password = forms.CharField(
        label="密码",
        min_length=4,
        max_length=12,
        error_messages={
            "required": "密码不能为空",
            "min_length": "密码最短4位",
            "max_length": "密码最长12位"
        },
        widget=forms.widgets.PasswordInput(
            attrs={"class": "form-control"}
        )
    )

    re_password = forms.CharField(
        label="确认密码",
        min_length=4,
        max_length=12,
        error_messages={
            "required": "密码不能为空",
            "min_length": "密码最短4位",
            "max_length": "密码最长12位",
        },
        widget=forms.widgets.PasswordInput(
            attrs={"class": "form-control"}
        )
    )

    phone = forms.CharField(
        label="手机号",
        min_length=11,
        max_length=11,
        validators=[
            RegexValidator(r'^\d{11}$', "手机号必须是数字"),
            RegexValidator(r'^1[356789][0-9]{9}$', "手机号格式不正确")
        ],
        error_messages={
            "required": "手机号不能为空",
            "min_length": "手机号码11位",
            "max_length": "手机号码11位",
        },
        widget=forms.widgets.TextInput(
            attrs={"class": "form-control"}
        )
    )

    # 局部钩子
    def clean_username(self):
        value = self.cleaned_data.get("username", "")
        if "金瓶梅" in value:
            raise ValidationError("金瓶梅是敏感字")
        elif models.UserInfo.objects.filter(username=value):
            raise ValidationError("该用户已经注册")

    # 全局钩子
    def clean(self):
        pwd = self.cleaned_data.get("password", "")
        re_pwd = self.cleaned_data.get("re_password", "")

        if re_pwd and pwd == re_pwd:
            return self.cleaned_data
        else:
            err_msg = "两次输入的密码不一致"
            self.add_error("re_password", err_msg)
            raise ValidationError(err_msg)

templates/article_detail.html
{% extends 'base.html' %}
{% block page-main %}
    <div class="article-detail">
        <h1 class="article-title">{{ article.title }}</h1>
        <div class="article-content">
            {{ article.articledetail.content|safe }}
        </div>
    </div>
    <div id="div_digg">
        <div class="diggit dig">
            <span class="diggnum" id="digg_count">{{ ariticle.up_count }}</span>
        </div>
        <div class="buryit dig">
            <span class="burynum" id="bury_count">{{ article.down_count }}</span>
        </div>
        <div class="clearfix"></div>
        <div class="diggword" id="digg_tips">
        </div>
    </div>

    <hr style="clear:both">

    <div class="comment-list">
        <h3>评论列表</h3>
        <ul class="list-group">
            {% for comment in comment_list %}
                {% if comment.parent_comment %}
                    <li class="list-group-item">
                        <p class="small"><span>#{{ forloop.counter }}楼</span> <span>{{ comment.create_time }}</span>
                            <a href="/blog/{{ comment.user.username }}/">{{ comment.user.username }}</a></p>
                        <div>
                            <p>@ <span>{{ comment.parent_comment.user.username }}</span></p>
                            <p class="well">{{ comment.content }}</p>
                        </div>
                    </li>
                {% else %}
                    <li class="list-group-item">
                        <p class="small"><span>#{{ forloop.counter }}楼<</span><span>{{ comment.create_time }}</span>
                            <a href="/blog/{{ comment.user.username }}/">{{ comment.user.username }}</a></p>>
                        <p>{{ comment.content }}</p>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
    </div>

    <div class="add-comment col-md-6">
        <h3>发表评论</h3>
        <div class="panel panel-success">
            <div class="panel panel-heading">
                <h3 class="panel-title">{{ request.user.username }}</h3>
            </div>
            <div class="panel-body">
                <p>评论内容</p>
                <textarea style="width: 100%" name="" id="" cols="30" rows="10">

                </textarea>
                <button class="btn btn-success pull-right">提交</button>
            </div>
        </div>
    </div>

{% endblock %}

{% block page-js %}
    <script>
        $("#div_digg").on("click", ".dig", function () {
            console.log(this);
            let isUp = $(this).hasClass("diggit");
            let articleId = '{{ article.nid }}';
            console.log(articleId);

            let userId = '{{ request.user.nid }}';
            if (!userId) {
                location.href = "/login/"
            } else {
                $.ajax({
                    url: "/updown/",
                    type: "POST",
                    data: {
                        article_id: articleId,
                        is_up: isUp,
                        user_id: userId
                    },
                    success: function (data) {
                        console.log(data);
                        if (data.code) {
                            $("#digg_tips").text(data.data);
                        } else {
                            if (isUp) {
                                let $upCount = $("#digg_count");
                                $upCount.text(+$upCount.text() + 1);
                            } else {
                                let $downCount = $("#bury_count");
                                $downCount.text(+$downCount.text() + 1);
                            }
                            $("#digg_tips").text(data.data);
                        }
                    }
                })
            }
        })


    </script>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en" class="">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ blog.title }}</title>
    <link rel="stylesheet" href="/static/mybbs.css">
    <link rel="stylesheet" href="/media/themes/{{ blog.theme }}">
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.min.css">
</head>
<body>

<div class="header">
    <p>{{ blog.title }} <a class="index-url" href="/index/">首页</a></p>
</div>

<div class="container-fluid main">
    <div class="row">
        <div class="col-md-3">
            {% load mytag %}
            {% left_panel username %}
        </div>
        <div class="col-md-9">
            {% block page-main %}
            {% endblock page-main %}
        </div>
    </div>
</div>

<script src="/static/jquery-3.3.1.min.js"></script>
<script src="/static/setupAjax.js"></script>

{% block page-js %}

{% endblock %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block page-main %}
    <div class="article-list">
        {% for article in article_list %}
            <div class="article">
                <div class="article-top">
                    <h2><a href="/blog/{{ username }}/article/{{ article.nid }}/">{{ article.title }}</a></h2>
                </div>
                <div class="article-middle">
                    <div class="media">
                        <div class="media-left media-middle">
                            <a href="#">
                                <img class="media-object article-avatar" src="/media/{{ article.user.avatar }}"
                                     alt="...">
                            </a>
                        </div>
                        <div class="media-body">
                            {{ article.desc }}
                        </div>
                    </div>
                </div>
                <div class="article-footer">
                    <span class="article-user"><a
                            href="/blog/{{ article.user.username }}/">{{ article.user.username }}</a></span>发布于
                    <span>{{ article.create_time }}</span>
                    <span class="glyphicon glyphicon-thumbs-up">点赞({{ article.up_count }})</span>
                    <span class="glyphicon glyphicon-comment">评论({{ article.comment_count }})</span>
                </div>
            </div>
        {% endfor %}

            {{ page_html|safe }}
    </div>
{% endblock %}

templates/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Index Page</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/mybbs.css">
</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">SH BBS</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">文章</a></li>
                <li><a href="#">招聘</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.username %}
                    <li><img class="avatar" src="/media/{{ request.user.avatar }}" alt=""></li>
                    <li><a href="#">{{ request.user.username }}</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">个人中心<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="/logout/">注销</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="/login/">登陆</a></li>
                    <li><a href="/reg/">注册</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">Panel title</h3>
                </div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="article-list">
                {% for article in article_list %}
                    <div class="article">
                        <div class="article-top">
                            <h2>{{ article.title }}</h2>
                        </div>
                        <div class="article_middle">
                            <div class="media">
                                <div class="media-left media-middle">
                                    <a href="#">
                                        <img class="media-object article-avatar" src="/media/{{ article.user.avatar }}"
                                             alt="">
                                    </a>
                                </div>
                                <div class="media-body">
                                    {{ article.desc }}
                                </div>
                            </div>
                        </div>
                        <div class="article-footer">
                            <span class="article-user"><a
                                    href="/blog/{{ article.user.username }}">{{ article.user.username }}</a></span>发布于<span>{{ article.create_time }}</span>
                            <span class="glyphicon glyphicon-thumbs-up">点赞({{ article.up_count }})</span>
                            <span class="glyphicon glyphicon-comment">评论({{ article.comment.count }})</span>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-2">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Panel title</h3>
                </div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
        </div>
    </div>
</div>

<script src="/static/jquery-3.3.1.min.js"></script>
<script src="/static/bootstrap-3.3.7/js/bootstrap.min.js"></script>

</body>
</html>

templates/left_tag.html
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>文章分类</h3>
    </div>
    <div class="panel-body">
        <ul class="list-unstyled">
            {% for category in category_list %}
                <li>
                    <a href="/blog/{{ username }}/category/{{ category.title }}">{{ category.title }}({{ category.num }})</a>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>



<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">文章标签</h3>
    </div>
    <div class="panel-body">
        <ul class="list-unstyled">
            {% for tag in tag_list %}
                <li><a href="/blog/{{ username }}/tag/{{ tag.title }}">{{ tag.title }}({{ tag.article_set.count}})</a></li>
            {% endfor %}
        </ul>
    </div>
</div>


<div class="panel panel-warning">
    <div class="panel-heading">
        <h3 class="panel-title">日期归档</h3>
    </div>
    <div class="panel-body">
        <ul class="list-unstyled">
            {% for archive in archive_list %}
                <li><a href="/blog/{{ username }}/archive/{{ archive.ym }}">{{ archive.ym }}({{ archive.num }})</a></li>
            {% endfor %}
        </ul>
    </div>
</div>

templates/login.html
<!doctype html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>欢迎登陆</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/mystyle.css">
</head>


<body>
<div class="container">
    <div class="row">
        <div class="md-offset-4" id="login-form">
            <form autocomplete="off" novalidate>

                <div class="form-group">
                    <label for="{{ form_obj.username.id_for_label }}">{{ form_obj.username.label }}</label>
                    {{ form_obj.username }}
                </div>

                <div class="form-group">
                    <label for="{{ form_obj.password.id_for_label }}">{{ form_obj.password.label }} </label>
                    {{ form_obj.password }}
                </div>

                <div class="form-group" id="v-code-wrapper">
                    <label for="{{ form_obj.password.id_for_label }}">验证码</label>
                    <input type="text" class="form-control" id="v-code-input">
                    <img src="/v_code/" alt="" id="v-code">
                </div>

                <button type="button" class="btn btn-success" id="login-button">登陆</button>
                <span class="error" id="login-error"></span>

            </form>
        </div>
    </div>
</div>


<script src="/static/jquery-3.3.1.min.js"></script>
<script src="/static/setupAjax.js/"></script>
<script>
    $(document).ready(function () {
        $("#login-button").click(function () {
            $.ajax({
                url: "/login/",
                type: "POST",
                data: {
                    username: $("#id_username").val(),
                    password: $("#id_password").val(),
                    v_code: $("#v-code-input").val()
                },
                success: function (data) {
                    if (!data.code) {
                        location.href = data.data;
                    } else {
                        $("#login-error").text(data.data)
                    }
                },
                error: function (err) {
                    console.log(err)
                }
            })
        });

        $("form_input").focus(function () {
            $("#login-error").text("")
        });

        $("#v-code").click(function () {
            let oUrl = this.src;
            if (/[?]$/.test(oUrl)) {
                this.src = "/v_code/"
            } else {
                this.src += "?";
            }
        });

    })

</script>

</body>
</html>

templates/login2.html
<!doctype html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>欢迎</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/mystyle.css">
</head>
<body>


<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4" id="login-form">
            <form autocomplete="off" novalidate>
                <div class="form-group">
                    <label for="{{ form_obj.username.id_for_label }}">{{ form_obj.username.label }}</label>
                    {{ form_obj.username }}
                </div>

                <div class="form-group">
                    <label for="{{ form_obj.password.id_for_label }}">{{ form_obj.password.label }}</label>
                    {{ form_obj.password }}
                </div>

                <button type="button" class="btn btn-success" id="login-button">登陆</button>
                <span class="error" id="login-error"></span>
                <div id="popup-captcha"></div>
            </form>
        </div>
    </div>
</div>

<script src="/static/jquery-3.3.1.min.js"></script>
<script src="/static/setupAjax.js"></script>
<script src="/static/gt.js"></script>

<script>
    let handlerPopup = function (captchaObj) {
        captchaObj.onSuccess(function () {
            let validate = captchaObj.getValidate();
            $.ajax({
                url: "/login2/",
                type: "post",
                data: {
                    username: $("#id_username").val(),
                    password: $("#id_password").val(),
                    geetest_challenge: validate.geetest_challenge,
                    geetest_validate: validate.geetest_validate,
                    geetest_seccode: validate.geetest_seccode
                },
                success: function (data) {
                    if (!data.code) {
                        location.href = data.data;
                    } else {
                        $("#login-error").text(data.data);
                    }
                },
                error: function (err) {
                    console.log(err)
                }
            });
        });

        $("#login-button").click(function () {
            captchaObj.show();
        });

        captchaObj.appendTo("#popup-captcha");
    };

    $.ajax({
        url: "/pcgetcaptcha?t=" + (new Date()).getTime(),
        type: "get",
        dataType: "json",
        success: function (data) {
            initGeetest({
                gt: data.gt,
                challenge: data.challenge,
                product: "popup", // 产品形式，包括：float，embed，popup。注意只对PC版验证码有效
                offline: !data.success // 表示用户后台检测极验服务器是否宕机，一般不需要关注
                // 更多配置参数请参见：http://www.geetest.com/install/sections/idx-client-sdk.html#config
            }, handlerPopup);
        }
    });

    $(document).ready(function () {
        $("form input").focus(function () {
            $("#login-error").text("");
        });

        $("#v-code").click(function () {
            this.src += "?";
        });
    })


</script>


</body>
</html>

templates/reg.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>欢迎注册</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.min.css">
    <style>
        .reg-form {
            margin-top: 70px;
        }

        #show-avatar {
            width: 80px;
            height: 80px;
        }
    </style>
</head>
<body>

<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3 reg-form">
            <form class="form-horizontal" autocomplete="off" novalidate>
                <div class="form-group">
                    <label for="{{ form_obj.username.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.username.label }}</label>
                    <div class="col-sm-10">
                        {{ form_obj.username }}
                        <span class="help-block"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="{{ form_obj.password.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.password.label }}</label>
                    <div class="col-sm-10">
                        {{ form_obj.password }}
                        <span class="help-block"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="{{ form_obj.re_password.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.re_password.label }}</label>
                    <div class="col-sm-10">
                        {{ form_obj.re_password }}
                        <span class="help-block"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="{{ form_obj.phone.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.phone.label }}</label>
                    <div class="col-sm-10">
                        {{ form_obj.phone }}
                        <span class="help-block"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">头像</label>
                    <div class="col-sm-10">
                        <input accept="image/*" type="file" id="id_avatar" name="avatar" style="display: none">
                        <label for="id_avatar"><img src="/static/img/default.png" id="show-avatar"></label>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="button" class="btn btn-success" id="reg-button">注册</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>

<script src="/static/jquery-3.3.1.min.js"></script>
<script src="/static/setupAjax.js"></script>

<script>
    $("#reg-button").click(function() {
        let dataObj = new FormData();
        dataObj.append("username", $("#id_username").val());
        dataObj.append("password", $("#id_password").val());
        dataObj.append("re_password", $("#id_re_password").val());
        dataObj.append("phone", $("#id_phone").val());
        dataObj.append("avatar", $("#id_avatar")[0].files[0]);
        $.ajax({
            url:"/reg/",
            processData:false,
            contentType:false,
            data:dataObj,
            success: function(data){
                console.log(data);
                if(data.code){
                    let errMsgObj = data.data;
                    $.each(errMsgObj, function (k,v) {
                        $("#id_"+k).next(".help-block").next(v[0]).parent().parent().addClass("has-error");
                    })
                }else{
                    console.log(data.data);
                    location.href = data.data || "/login/"
                }
            }
        })
    });

    $("input.form-control").focus(function() {
        $(this).next(".help-block").text("").parent().parent().removeClass("has-error");
    });

    $("#id_avatar").change(function() {
        let fileObj = this.files[0];
        console.log(fileObj);
        let fileReader = new FileReader();
        fileReader.readAsDataURL(fileObj);
        fileReader.onload = function(){
          $("#show-avatar").attr("src",fileReader.result);
        };
    })

</script>

</body>
</html>